// code-snippet/scheduler-sdk/react/datetime-picker/default-cs10/app/index.tsx


// import the datetimepicker component
import {DateTimePickerComponent } from '@syncfusion/ej2-react-calendars';
import * as React from 'react';
import * as ReactDOM from 'react-dom';

function App() {

    // initialize the value, min and max
    const minDate: Date = new Date("11/22/2019 12:00 PM");
    const maxDate: Date = new Date("11/25/2019 5:00 PM");
    return <DateTimePickerComponent id="datetimepicker" min={minDate} max={maxDate} />;
}
ReactDOM.render(<App />, document.getElementById('element'));

// code-snippet/scheduler-sdk/vue/time-picker/min-max-cs1/app.vue
<template>
  <div id="app">
    <div class='wrapper'>
      <ejs-timepicker :min="minDate" :max="maxDate" :value="timeVal"></ejs-timepicker>
    </div>
  </div>
</template>
<script>
import { TimePickerComponent } from '@syncfusion/ej2-vue-calendars';

export default {
  name: "App",
  components: {
    'ejs-timepicker': TimePickerComponent
  },
  data() {
    return {
      minDate: new Date("05/07/2017 7:00 AM"),
      maxDate: new Date("05/07/2017 4:00 PM"),
      timeVal: new Date("05/27/2017 1:00 PM")
    }
  }
}
</script>
<style>
@import '../node_modules/@syncfusion/ej2-base/styles/material3.css';
@import '../node_modules/@syncfusion/ej2-inputs/styles/material3.css';
@import '../node_modules/@syncfusion/ej2-popups/styles/material3.css';
@import '../node_modules/@syncfusion/ej2-lists/styles/material3.css';
@import "../node_modules/@syncfusion/ej2-vue-calendars/styles/material3.css";

.wrapper {
  max-width: 250px;
  margin: 0 auto;
}
</style>
